### ISSUE TITLE
Please add opacity. transparent 

### ISSUE THREAD

**Issue by ApoorvShah** [xiyaowong/transparent.nvim#33]
Some variable that controls opacity for neovin would be great!

**Comment by dedguy21** [comment]
might want to refer to:

https://stackoverflow.com/questions/63784128/vim-nvim-background-opacity

Then try a window manager or terminal (gpu type like kitty or wezterm) that will has opacity features. I say wezterm because it's crazy configurable through lua, which you are already using with neovim.
